version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: datawow
      POSTGRES_PASSWORD: datawow
      POSTGRES_DB: datawowdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
